# Generated by Django 5.0.1 on 2024-01-09 17:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocrllm', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='hintexplanation',
            old_name='explanation_text',
            new_name='hint_or_explanation_text',
        ),
        migrations.RenameField(
            model_name='hintexplanation',
            old_name='hint_text',
            new_name='user_input',
        ),
        migrations.AddField(
            model_name='hintexplanation',
            name='user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
